### ISSUE TITLE
Can't find the label of each instance

### ISSUE THREAD

**Issue by jinmyeongAN** [znhy1024/HEARD#3]
## Problem
I can't find the label(rumor or non-rumor) of each instance.
As you said in the [README](https://github.com/znhy1024/HEARD#obtain-beard-dataset)
There are 2 kinds of file
1. BEARD_info.json
2. BEARD.json

And each file of data format is exactly same as you said
However, there're no label(rumor or non-rumor) information

I can find the text of twitter using the Twitter API and `post_ids`
But, Can't find the label

## Question
1. Does the Instance ID represent the rumor or non-rumor?
    - I could find Instance ID has 2 kinds of prefix `N `and `S`
    - So, I was wondering if the prefix show the label or not
   
2. How can I get the label data of each Instance ID if Question 1 is False ? 

Thank you 🙂

**Comment by znhy1024** [comment]
Yes, the instances with prefix S are rumor while those with prefix N are non-rumor.

**Comment by jinmyeongAN** [comment]
Thank you! I totally understood :)
